### ISSUE TITLE
Firefox blocks public spreadshet data?

### ISSUE THREAD

**Issue by markbarratt** [markbarratt/okf-events-a#4]
Cedric says: the text as pulled from the spreadsheet does not appear if you’re looking at it using Firefox, due to the baked in anti-tracking feature. When I deactivate it for the page it appears. We may have to look at technical solutions to go around that.

**Comment by markbarratt** [comment]
Quick test on Mac Firefox https://markbarratt.github.io/okf-events-a/firstpage/ and https://markbarratt.github.io/okf-events-a/gis-1/ gives no problems. Will explore in Windows when I can get to a machine.

**Comment by clombion** [comment]
I did additional testings and the issue was related to NoScript, and not Firefox itself. So the issue can be closed.
